project:
  type: website
  output-dir: docs

website:
  title: "Dive into Jimin"
  description:
    Jimin's personal website 
  site-url: "https://jiminhong123.github.io/my-website/"
  navbar:
    background: primary
    search: false
    
format:
  html:
    theme: cosmo
    toc: false

editor:
  mode: source